# Generated by Django 3.2.5 on 2021-08-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Recently_Updated', models.DateTimeField(verbose_name='date Updated')),
                ('Date_Added', models.DateTimeField(verbose_name='date Added')),
            ],
        ),
    ]
