# Generated by Django 3.2.5 on 2021-08-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='No_of_stocks',
            field=models.IntegerField(default=0),
        ),
    ]
